### ISSUE TITLE
Error in server response

### ISSUE THREAD

**Issue by AuPath** [dwcoates/pygn-mode#129]
I get this error when i call pygn functions to display a board, any idea why?

pygn-mode--parse-response: Bad response from ‘pygn-mode’ server -- no :version. Attempted restat

**Comment by rolandwalker** [comment]
Hi!  What output do you get when you run

<kbd>M-x</kbd> `pygn-mode-dependency-check`

?

**Comment by AuPath** [comment]
Hi, thanks for the quick response!

I get "All pygn-mode dependencies verified."

**Comment by rolandwalker** [comment]
Great!  The mode also expects that this Python file https://github.com/dwcoates/pygn-mode/blob/master/pygn_server.py exists in the same directory as `pygn-mode.el`.  If that file is not present, you would get the "no :version" error message.

The error message should be made more clear, and the dependency check could also be improved to check for the existence of the file.

**Comment by AuPath** [comment]
The files are in the same directory, i use Straight to download the repo/package so i should have all the files in the same places as this repo.

**Comment by rolandwalker** [comment]
Interesting.  We've never tested this software on Windows; let me know if that's your platform.

You can confirm that the server is not running at all if the following returns nil:

<kbd>M-:</kbd>`(pygn-mode--server-running-p)`<kbd>RET</kbd>

You can double-check the command that the package is using to start the server by seeing what this returns:

<kbd>M-:</kbd>`(list pygn-mode-python-executable "-u" (expand-file-name "pygn_server.py" pygn-mode-script-directory) "-")`<kbd>RET</kbd>

And you can try running that command at your shell command line (without the parentheses).

**Comment by AuPath** [comment]
I figured out what the problem was, Straight downloads the content of a repository under a "../straight/repos" folder which contains all files. The .el files that actually run are under a "../straight/build" folder which did not contain the "pygn_server.py" file. Simply copying this file under the build folder solved this problem for me. Thank you for your help!

**Comment by rolandwalker** [comment]
Oh, I see, Straight builds a symlink farm like https://github.com/raxod502/straight.el#what-does-this-look-like-on-disk .

It looks like you can tell Straight to link in the `*.py` file using `:files` keyword.

It's still true that the `pygn-mode.el` error message is poor.

I'm glad you discovered this package!  Note that while I do use it myself, @dwcoates and I never got it to the point that it could be considered finished.
