### ISSUE TITLE
Black pawns are painted white

### ISSUE THREAD

**Issue by pedrormjunior** [dwcoates/pygn-mode#206]
Black pawns, that should be black, are faced white, as shown in the screenshot below. (Also tested by loading Emacs with no init and a new fresh installation of pygn-mode.)
![2023-03-20-204825_563x563_scrot](https://user-images.githubusercontent.com/630946/226489716-14a98e33-d4ba-4a14-a747-fc9f3a5e1353.png)

PGN example:
```
[Event "Testing PyGN"]
[Site "localhost"]
[Date "2023.03.20"]
[Round "?"]
[White "Player1"]
[Black "Player2"]
[Result "*"]

1. e4
*
```

I saw that `pygn-mode-pgn-to-board` is already returning the missing `fill=#000` information for the `"black-pawn"` in SVG... Inside that function, we find a call to `pygn-mode--server-query` and, from that one, a call to `pygn-mode--server-send`.  From inside the last one, when `process-send-string` is called and writes out the Python server response on ` *pygn-mode-server*` buffer, the `fill=#000` is already missing...

Strangely, when the same string that is given as `STRING` argument to `process-send-string` is input on the server running on the terminal (with the same command `python -u /home/username/.emacs.d/elpa/pygn-mode-20220531.1422/pygn_server.py -`), it has some extra information before the SVG and does not lack the `fill=#000` information for the `"black-pawn"`...

Any hints for the difference on server response when it is running form terminal compared to Emacs' one?

Why just `fill=#000` for black pawn is missing among that cumbersome SVG information when server on Emacs is in play? (Remember, by running the PyGN server on terminal, it DOES return the information correctly.)

**Comment by pedrormjunior** [comment]
Hi Roland Walker and others. Indeed, `chess` library when running the server from Emacs is version 1.6.1 while the most recent version of `chess`, the one employed from terminal, is 1.9.4. I've also noticed that this version 1.6.1 comes with PyGN, i.e., is is located in `/home/username/.emacs.d/elpa/pygn-mode-20220531.1422/lib/python/site-packages/chess/__init__.py`, inside PyGN installation directory.

As the version of `chess` is fixed by PyGN, are not other people having the same problem of mine?

How can I employ the last version of `chess` along with PyGN? (It is not enough to remove the `chess` Python package from PyGN installation, as the `pygn-mode--parse-response` seems to require updates to work along with version 1.9.4 of `chess`.)

**Comment by rolandwalker** [comment]
Aha!  Thanks for the diagnosis.  That should be enough knowledge to fix, and the answer should involve upgrading the bundled `chess` library.  Though it sounds like some other work must be done to make `pygn-mode--parse-response` function with the latest `chess` library.

**Comment by rolandwalker** [comment]
@dwcoates I can now duplicate this bug, and what's interesting is that my Black pawns are gray — a little different than the White pawns.

![last image](https://user-images.githubusercontent.com/727482/229296923-1e2c9f46-859a-4924-9829-7c54611773a8.png)

**Comment by pedrormjunior** [comment]
Probably the gray color is due to `dimmer-mode`, right? I've noticed it as well... :-) Soon I'll check the update, thanks in advance.

**Comment by pedrormjunior** [comment]
Working nicely! Very appreciated!
