### ISSUE TITLE
Accept starting position of FEN tag

### ISSUE THREAD

**Issue by balbirthomas** [dwcoates/pygn-mode#213]
There seems to be no way to set a custom starting position for the board even though the first move does honor the `FEN` tag. Shouldn't `pygn-mode-display-gui-board-at-pos` check if a `FEN` tag is present and setup the board to the corresponding position ? The FEN position only takes affect after the first move (`pygn-mode-next-move-follow-board`) is executed. This makes it difficult for instance to use a PGN file that is meant to be a puzzle.

**Comment by rolandwalker** [comment]
@balbirthomas like #212 this was also fixed long ago, and it should be apparent when you upgrade to the newly-tagged version.

**Comment by balbirthomas** [comment]
Thanks @rolandwalker . I can confirm this issue is indeed fixed by upgrading to v0.6.3 on MELPA stable. Apologies for the trouble. Closing issue.
