### ISSUE TITLE
Create a new repo for uci-mode

### ISSUE THREAD

**Issue by rolandwalker** [dwcoates/pygn-mode#95]
Per https://github.com/dwcoates/pygn-mode/pull/92/files#diff-96c9fc246f6b0220f76428b02d085cd2R40

`uci-mode.el` already anticipates being in its own repo.

I have put multiple libraries inside the same repo before, and my memory is that it is simpler dealing with MELPA when they are separated.

**Comment by dwcoates** [comment]
Okay, will create.

**Comment by rolandwalker** [comment]
fully fixed in #125
